apiVersion: apps/v1
kind: Deployment
metadata:
  name: honk-twitter-bot
  labels:
    app.kubernetes.io/name: honk-twitter-bot
    app.kubernetes.io/managed-by: honk
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: honk-twitter-bot
      app.kubernetes.io/managed-by: honk
  template:
    metadata:
      labels:
        app.kubernetes.io/name: honk-twitter-bot
        app.kubernetes.io/managed-by: honk
    spec:
      containers:
      - name: honk
        image: ctadeu/honk_twitter_bot:0.2
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: Always
        volumeMounts:
        - name: honk-twitter-config
          mountPath: /app/config
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: 128Mi
            cpu: 100m
      volumes:
        - name: honk-twitter-config
          secret:
            secretName: honk-twitter-config
